### ISSUE TITLE
Problem with EBE program generation

### ISSUE THREAD

**Issue by koudis** [mark-sed/ebe#13]
Hi Marek,

I want to use your tool for JSON files edit.

It does not work. Once I run `ebe -in <file>.json -out <file>_new.json -oe program` program will block and never returns (I let it be thru the night).

Input files as an attachment.

I have compiled it from the source code, actual master, commit id b2edc6e5eef37ddafdd408ab9c4cfec5a18af09c

[input_files.zip](https://github.com/mark-sed/ebe/files/8682517/input_files.zip)

**Comment by mark-sed** [comment]
Hello,
the problem here is that you're trying to use Ebe **to change string value** from `ubuntu1804` to `ubuntu2204`, but unfortunately **this is not a task suited for Ebe**. Firstly, because in the current version string modification is not yet available (hopefully that will change in the near future) and secondly, since **this is not a repeating pattern**.

You're giving Ebe 2 whole files, but this already indicates very difficult editing task and rather not a possible one. If you are able to express desired edits for the whole file on one line or few lines of the input file, then you're usually good to go. 

There are some examples in the readme file, but currently Ebe is good to employ there, where you have all the line of the same structure, such as csv, tsv, gtf, ini...

Hopefully my response made it more clear (I'll gladly explain more in detail if you'd like) and thank you for testing out the tool.

**Comment by koudis** [comment]
ok, I tried to create on-line JSON, same problem.

If I create a Json array filled in with a.json data, copy the resulting file, update values and apply ebe... will the result be better?

**Comment by mark-sed** [comment]
Creating one line json is possible with Ebe, but it is not possible to in all cases reduce the number of whitespace to 0.
The problem is that, each line might have different number of white spaces in front of it and then it is not possible to create one exact example, which would work for all of them. Ebe has no way of knowing that you want to delete all spaces and not just 2 of them.

But if you want to just make one line json and you don't mind the extra whitespaces, then it's no problem. I would only recommend using at least 3-5 line examples, since once again using just 2 lines, makes it harder for ebe to decide if you want to concatenate all the lines or just the first 2 or 3 lines.

Example input file `in.json`:
```
{
  'a': 42,
  'b': 43,
  'c': 108,
```  
Example output file `out,json`:
```
{  'a': 42,  'b': 43,  'c': 108,
```  
and then as you did: `ebe -in in.json -out out.json -eo concat.ebel` or if you already have the file or files you want to edit you can use:
```
ebe -x -in in.json -out out.json file1.json file2.json -o ./
```

**Comment by mark-sed** [comment]
> If I create a Json array filled in with multiple <file>.json data, copy the resulting file, update values and apply ebe... will the result be better?

Well not exactly 100 % sure what you mean, but as I mentioned, changing string is not yet possible, so Ebe cannot change values to different ones, unless those values are integers or floats, which already have a support in form of user defined expression. In this case an exact expression has to be given since there are infinite many possible ones and once again Ebe cannot find the exact one

Example input file `in.json`:
```
[0,
```
Example output file `out.json`:
```
 {! $*2 !},
```  
And then run over file `data.json`:
```json
{
[0,
 42,
 8,
 102
]
}
```
will result in:
```
{
[0,
 84,
 16,
 204
]
}
```
Just note that for this the `-expr` command line option has to be set and notice that all the numbers are in the same column (there is either space or `[` in front of them).
